config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources "places"
  # Defines the root path route ("/")
  # get("/", { :controller => "articles", :action => "index" })
  get '/places' => 'places#index'
  get '/places/new' => 'places#new', as: "newplace"
  post '/places' => 'places#create'
  get '/places/:id' => 'places#show', as: "placeshow"
  get '/entries/new/:place_id' => 'entries#new', as: 'new_entry'
  post '/entries/:place_id' => 'entries#create', as: 'create_entry'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  # talks to the "entries" table
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  # talks to the "places" table
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @place = Place.find(params["place_id"]) 
    @entry = Entry.new  
  end

  def create
    @place = Place.find(params["place_id"]) 
    @entry = Entry.new(entry_params)  
    @entry.place_id = @place.id  

    if @entry.save
      puts "Entry added successfully." 
      redirect_to place_path(@place)  
    else
      puts "Failed to add entry."    
      redirect_to new_place_entry_path(@place)  
    end
  end

  def entry_params
    params.require(:entry).permit(:title, :date, :description)
  end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find (params["id"])
   
  end

  def new
    @place = Place.new
   
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      puts "Place was successfully created."
      redirect_to places_path
    else
      puts "Failed to create place."
      redirect_to new_place_path
    end
  end

  def place_params
    params.require(:place).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>Add New Entry for <%= @place.name %></h1>
<form action="<%= create_entry_path(@place) %>" method="post">
 <input type="hidden" name="entry[place_id]" value="<%= @place.id %>">
 
 <p>
  <label for="title">Title:</label>
  <input type="text" name="entry[title]" id="title">
 </p> 

<p>  
  <label for="date">Date:</label>
  <input type="date" name="entry[date]" id="date">
 </p> 

  <p>
  <label for="description">Description:</label>
  <input type="text" name="entry[description]" id="description">
 </p>

 

  <input type="submit" value="Create Entry">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places I’ve Been</h1>

<ul>
  <% for place in @places %>  
  <li><a href="/places/<%= place.id %>"><%= place.name %></a></li>
  <% end %>
</ul>

<a href="/places/new" class="button">New Place</a>

app/views/places/new.html.erb
<h1>Add a New Place</h1>

<form action="/places" method="POST">
  <p>
  <label for="place_name">Name of the Place:</label>
  <input type="text" id="place_name" name="place[name]">
  </p>
  
  <button type="submit">Create Place</button>
</form>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<ul>
  <% for entry in @place.entries %>
    
      <p>
        <strong>Title:</strong> <%= entry.title %><br>
        <% if entry.posted_on %>
          <strong>Date:</strong> <%= entry.posted_on.strftime("%Y-%m-%d") %><br>
        <% else %>
          <strong>Date:</strong> Date not available<br>
        <% end %>
        <strong>Description:</strong> <%= entry.description %>
      </p>
    
  <% end %>
</ul>

<p>
<a href="<%= new_entry_path(@place) %>">New Post</a>
</p>

<p>
<a href="/places">Back to Places</a>
</p>